package com.awnish.calculator.ui

import android.content.Context
import android.graphics.BitmapFactory
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.biometric.BiometricManager
import androidx.biometric.BiometricPrompt
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.awnish.calculator.data.database.PhotoEntity
import com.awnish.calculator.data.repository.GalleryRepository
import kotlinx.coroutines.launch
import java.text.DateFormat

private enum class Section(val title: String) { CALCULATOR("Calculator"), GALLERY("Private Gallery"), SETTINGS("Settings") }
@Composable fun AwnishApp(activity: android.app.Activity) { var section by rememberSaveable { mutableStateOf(Section.CALCULATOR) }; var unlocked by rememberSaveable { mutableStateOf(false) }; val prefs=remember { activity.getSharedPreferences("settings", Context.MODE_PRIVATE) }; DisposableEffect(activity) { val observer=object: androidx.lifecycle.DefaultLifecycleObserver { override fun onStop(owner: androidx.lifecycle.LifecycleOwner) { unlocked=false } }; (activity as androidx.lifecycle.LifecycleOwner).lifecycle.addObserver(observer); onDispose { (activity as androidx.lifecycle.LifecycleOwner).lifecycle.removeObserver(observer) } }
    Scaffold(bottomBar = { NavigationBar { Section.entries.forEach { s -> NavigationBarItem(selected=section==s,onClick={section=s},icon={Icon(if(s==Section.CALCULATOR) Icons.Default.Calculate else if(s==Section.GALLERY) Icons.Default.PhotoLibrary else Icons.Default.Settings,s.title)},label={Text(s.title)}) } } }) { pad -> Box(Modifier.padding(pad)) { when(section) { Section.CALCULATOR -> CalculatorScreen(); Section.GALLERY -> GalleryGate(activity, unlocked, {unlocked=true}, prefs.getBoolean("lock",true)); Section.SETTINGS -> SettingsScreen(prefs) } } }
}
@Composable private fun GalleryGate(activity: android.app.Activity, unlocked:Boolean, onUnlocked:()->Unit, lock:Boolean) { if(!lock || unlocked) GalleryScreen() else Column(Modifier.fillMaxSize().padding(32.dp),verticalArrangement=Arrangement.Center,horizontalAlignment=Alignment.CenterHorizontally) { Icon(Icons.Default.Lock,"",modifier=Modifier.size(56.dp)); Spacer(Modifier.height(16.dp)); Text("Private Gallery",style=MaterialTheme.typography.headlineSmall); Text("Your encrypted photos are protected by your device authentication.",modifier=Modifier.padding(vertical=8.dp)); Button(onClick={ authenticate(activity,onUnlocked) }) { Text("Unlock gallery") } } }
private fun authenticate(activity: android.app.Activity, success:()->Unit) { val allowed=BiometricManager.Authenticators.BIOMETRIC_STRONG or BiometricManager.Authenticators.DEVICE_CREDENTIAL; if(BiometricManager.from(activity).canAuthenticate(allowed)!=BiometricManager.BIOMETRIC_SUCCESS) return; BiometricPrompt(activity,ContextCompat.getMainExecutor(activity),object:BiometricPrompt.AuthenticationCallback(){override fun onAuthenticationSucceeded(result:BiometricPrompt.AuthenticationResult){success()}}).authenticate(BiometricPrompt.PromptInfo.Builder().setTitle("Unlock Private Gallery").setSubtitle("Authenticate to view encrypted photos").setAllowedAuthenticators(allowed).build()) }
@Composable private fun GalleryScreen() { val context=LocalContext.current; val repo=remember { GalleryRepository(context) }; val scope=rememberCoroutineScope(); var query by rememberSaveable { mutableStateOf("") }; val photos by repo.photos(query).collectAsStateWithLifecycle(emptyList()); var selected by remember { mutableStateOf<PhotoEntity?>(null) }; var error by remember { mutableStateOf<String?>(null) }; val picker=rememberLauncherForActivityResult(ActivityResultContracts.PickMultipleVisualMedia(50)) { uris -> scope.launch { uris.forEach { runCatching { repo.import(it) }.onFailure { error=it.message ?: "Import failed; original image was not changed." } } } }
    Column(Modifier.fillMaxSize().padding(16.dp)) { Row(verticalAlignment=Alignment.CenterVertically) { Text("Private Gallery",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.weight(1f)); Icon(Icons.Default.VerifiedUser,"Encrypted locally") }; OutlinedTextField(query,{query=it},Modifier.fillMaxWidth().padding(top=12.dp),placeholder={Text("Search private photos")},singleLine=true,leadingIcon={Icon(Icons.Default.Search,null)}); error?.let{Text(it,color=MaterialTheme.colorScheme.error)}; if(photos.isEmpty()) Box(Modifier.weight(1f).fillMaxWidth(),contentAlignment=Alignment.Center){Text("No private photos yet\nImport creates an encrypted copy; originals stay untouched.",textAlign=androidx.compose.ui.text.style.TextAlign.Center)} else LazyVerticalGrid(GridCells.Adaptive(112.dp),Modifier.weight(1f).padding(top=12.dp),verticalArrangement=Arrangement.spacedBy(8.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){items(photos,key={it.id}){PhotoCard(it,repo){selected=it}}}; ExtendedFloatingActionButton(onClick={picker.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))},modifier=Modifier.align(Alignment.End),icon={Icon(Icons.Default.Add,null)},text={Text("Add photos")}) }
    selected?.let { PhotoViewer(it,repo,onClose={selected=null},onError={error=it}) }
}
@Composable private fun PhotoCard(photo:PhotoEntity, repo:GalleryRepository, open:()->Unit) { var bitmap by remember(photo.id){mutableStateOf<android.graphics.Bitmap?>(null)}; LaunchedEffect(photo.id){bitmap=runCatching { val bytes = repo.bytes(photo); BitmapFactory.decodeByteArray(bytes, 0, bytes.size) }.getOrNull()}; Card(Modifier.aspectRatio(1f).clickable{open()}) { bitmap?.let { Image(it.asImageBitmap(),photo.displayName,Modifier.fillMaxSize(),contentScale=ContentScale.Crop) } ?: Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Icon(Icons.Default.Image,"Encrypted image loading")} } }
@Composable private fun PhotoViewer(photo:PhotoEntity,repo:GalleryRepository,onClose:()->Unit,onError:(String)->Unit) { val scope=rememberCoroutineScope(); var bitmap by remember {mutableStateOf<android.graphics.Bitmap?>(null)}; var confirm by remember{mutableStateOf(false)}; LaunchedEffect(photo.id){runCatching{repo.bytes(photo)}.onSuccess{bitmap=BitmapFactory.decodeByteArray(it,0,it.size)}.onFailure{onError("Could not decrypt this image. It has not been deleted.")}}; AlertDialog(onDismissRequest=onClose,title={Text(photo.displayName)},text={Column { bitmap?.let{Image(it.asImageBitmap(),photo.displayName,Modifier.fillMaxWidth().heightIn(max=480.dp),contentScale=ContentScale.Fit)}; Text("${photo.mimeType} • ${DateFormat.getDateTimeInstance().format(photo.createdAt)}") }},confirmButton={TextButton(onClick={scope.launch{runCatching{repo.export(photo)}.onSuccess{onError("Exported to Pictures/AWNISH Exports")}.onFailure{onError("Export failed: ${it.message}")}}}){Text("Export")}},dismissButton={Row {TextButton(onClick={onClose}){Text("Close")}; TextButton(onClick={confirm=true}){Text("Delete")}}}); if(confirm) AlertDialog(onDismissRequest={confirm=false},title={Text("Move photo to trash?")},text={Text("The encrypted copy will be marked deleted. This action does not affect the original photo." )},confirmButton={TextButton(onClick={scope.launch{repo.trash(photo);onClose()}}){Text("Move to trash")}},dismissButton={TextButton(onClick={confirm=false}){Text("Cancel")}}) }
@Composable private fun SettingsScreen(prefs:android.content.SharedPreferences) { var lock by remember {mutableStateOf(prefs.getBoolean("lock",true))}; var precision by remember {mutableStateOf(prefs.getInt("precision",12))}; Column(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Settings",style=MaterialTheme.typography.headlineMedium); Text("Security",style=MaterialTheme.typography.titleMedium); ListItem(headlineContent={Text("Gallery lock")},supportingContent={Text("Use biometrics or device credential")},trailingContent={Switch(lock,{lock=it;prefs.edit().putBoolean("lock",it).apply()})}); Text("Gallery automatically locks when the app moves to the background."); HorizontalDivider(); Text("Calculator",style=MaterialTheme.typography.titleMedium); ListItem(headlineContent={Text("Decimal precision")},supportingContent={Text("Results use safe decimal arithmetic (up to $precision significant digits).")}); HorizontalDivider(); Text("Privacy",style=MaterialTheme.typography.titleMedium); Text("Imported images are encrypted and stored only in app-private storage. They are never uploaded. No account, analytics, tracking, advertising SDK, or broad media permission is used."); Text("About",style=MaterialTheme.typography.titleMedium); Text("AWNISH Calculator 1.0.0") } }
